name: Run benchmarks

on:
  schedule:
    - cron: "0 0 */1 * *"
  workflow_dispatch:

jobs:
  benchmark_single:
    runs-on: ubicloud-standard-8
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: windmill
          POSTGRES_PASSWORD: changeme
          POSTGRES_INITDB_ARGS: "-c shared_buffers=2GB -c work_mem=32MB -c effective_cache_size=4GB"
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
          --shm-size=2g
          --network host


      windmill:
        image: ghcr.io/windmill-labs/windmill-ee:main
        env:
          DATABASE_URL: postgres://postgres:changeme@localhost:5432/windmill
          LICENSE_KEY: ${{ secrets.WM_LICENSE_KEY_CI }}
          WORKER_GROUP: main
          WORKER_TAGS: deno,bun,go,python3,bash,dependency,flow,nativets
        options: >-
          --pull always --health-interval 10s --health-timeout 5s
          --health-retries 5 --health-cmd "curl
          http://localhost:8000/api/version"
        ports:
          - 8000:8000
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x
      - name: benchmark
        timeout-minutes: 30
        run: deno run --unstable -A -r
          https://raw.githubusercontent.com/windmill-labs/windmill/${GITHUB_REF##ref/head/}/benchmarks/benchmark_suite.ts
          -c
          https://raw.githubusercontent.com/windmill-labs/windmill/${GITHUB_REF##ref/head/}/benchmarks/suite_config.json
